open_collective: mixcore
patreon: mixcore
custom: ["https://www.paypal.me/mixcore"]
#ko_fi: mixcore
#liberapay: mixcore
#community_bridge: mixcore
#tidelift: mixcore/mix.core
#issuehunt: mixcore
#otechie: mixcore
#custom: ["https://www.paypal.me/mixcore", "https://www.buymeacoffee.com/mixcore"]
