# These are supported funding model platforms

github: [nhathoang989, Smilefounder, Sint94]
patreon: mixcore
open_collective: mixcore
ko_fi: mixcore
tidelift: mixcore/mix.core
community_bridge: mix-core
liberapay: mixcore
issuehunt: smilefounder
otechie: mixcore
