version: "3"
services:
    mixcore:
        build: .
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
            - sqlserver
            - mysql
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        restart: always
    # redis:
    #     image: redis
    mysql:
        image: mysql:8.0
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_DATABASE: mixcore
          MYSQL_USER: root
          MYSQL_PASSWORD: P@ssw0rd
        ports:
        - 3306:3306
volumes:
    db_data: {}